name: Call Summarizer Azure Function

on: 
  push:
    branches:
      - 'main' # Replace with the branch you want to monitor

jobs:
  trigger-function:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'article:')
    steps:
      - name: Call Function
        env:
            FUNCTION_URL: ${{ secrets.FUNCTION_URL }}
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          ARTICLE_NAME=$(echo $COMMIT_MESSAGE | awk '{print $2}')
          curl -X POST  $FUNCTION_URL \
               -H "Content-Type: application/json" \
               --data "{\"article_keyword\": \"$KEYWORD\"}"